import { useState } from 'react'
import { api } from '../../api'
import { Badge, Confirm, Empty, ErrorNotice, Icon, Loading, Modal, PageHeader, Refresh } from '../../components'
import { useAction, useResource } from '../../hooks'
import { AccountEditor, BandwidthEditor, ResourceEditor } from './Editors'
import { billUsable, charge, message, status, time } from './types'
import type { Account, Operation, Overview, Resource } from './types'
import './alicloud.css'

const gb = (bytes: string) => (Number(bytes) / 1024 ** 3).toLocaleString('zh-CN', { maximumFractionDigits: 3 })
type Editor = { type: 'account'; value?: Account } | { type: 'resource'; value?: Resource } | { type: 'bandwidth'; value: Resource }
export default function Alicloud() {
  const [editing, setEditing] = useState<Editor | null>(null), [removing, setRemoving] = useState<{ type: 'accounts' | 'resources'; id: string; name: string } | null>(null)
  const [dismiss, setDismiss] = useState<Operation | null>(null), [verified, setVerified] = useState(false)
  const overview = useResource<Overview>('/api/plugins/alicloud', editing || removing || dismiss ? 0 : 5000), action = useAction()
  const data = overview.data, available = Boolean(data && !overview.error)
  const done = () => { setEditing(null); setRemoving(null); setDismiss(null); overview.reload() }
  const open = (editor: Editor) => { action.clearError(); setEditing(editor) }
  return <div className="cloud-page"><PageHeader eyebrow="云服务插件" title="阿里云 CDT 与带宽" description="查看云账号流量与账单，管理 ECS 固定公网 IP、独立 EIP 的带宽和自动降速。"><Refresh onClick={overview.reload} /><button className="button button-primary" disabled={!available || action.busy || (data?.accounts.length ?? 8) >= 8} onClick={() => open({ type: 'account' })}><Icon name="plus" size={16} />添加云账号</button></PageHeader>
    <ErrorNotice message={overview.error || action.error} retry={overview.reload} />
    <div className="notice quiet-notice"><Icon name="activity" /><div><strong>流量查询、账单与免费额度分别核对</strong><p>兼容 CDT-Monitor 的国内 / 海外用量查询只用于展示；自动降速依据带账期的完整 CDT 账单，数据存在延迟。免费额度与开通状态请在<a href="https://cdt.console.aliyun.com/" target="_blank" rel="noreferrer">阿里云 CDT 控制台</a>核对。</p></div></div>
    {!data && overview.loading ? <Loading /> : !data ? <Empty title="云服务状态暂不可用" description="请刷新后再管理账号和资源。" /> : <>
      {!data.accounts.length && <section className="panel"><Empty title="尚未添加云账号" description="添加账号后登记需要管理的资源。凭据只保存在面板，自动控制默认关闭。" /></section>}
      <div className="cloud-accounts">{data.accounts.map(account => <section className="panel" key={account.id}>
        <div className="panel-heading"><h2>{account.name}</h2><Badge tone={account.enabled && !account.error_code ? 'good' : 'neutral'}>{account.enabled ? account.site === 'china' ? '中国站账号' : '国际站账号' : '已停用'}</Badge></div>
        <div className="panel-body"><div className="cloud-metrics"><div><span>中国内地用量（兼容读数）</span><strong>{account.traffic ? gb(account.traffic.mainland_bytes) : '—'} <small>GB</small></strong></div><div><span>海外用量（兼容读数）</span><strong>{account.traffic ? gb(account.traffic.overseas_bytes) : '—'} <small>GB</small></strong></div><div><span>{account.bill?.month ?? '当月'} 已出账 CDT 合计</span><strong>{account.bill?.usage_micro_gb != null ? (account.bill.usage_micro_gb / 1e6).toLocaleString('zh-CN', { maximumFractionDigits: 3 }) : '—'} <small>GB</small></strong></div></div>
          <p className="helper">兼容读数更新：{time(account.traffic?.queried_at ?? null)}；账单更新：{time(account.bill?.queried_at ?? null)}。旧值保留供查阅，不代表当前数据。</p>
          {(account.error_code || account.traffic_error) && <ErrorNotice message={[account.error_code && `账单：${message(account.error_code)}`, account.traffic_error && `兼容用量：${message(account.traffic_error)}`].filter(Boolean).join('；')} />}
          <p className="cloud-policy">自动控制：{account.auto_enabled && account.enabled ? `达到 ${account.limit_gb} GB 后降低已选资源带宽` : '已关闭'} · {billUsable(account) ? '账单可用于判断' : '等待当月完整、有效的 GB 单位账单'}</p>
          <details><summary>查看 CDT 账单项目（{account.bill?.rows.length ?? 0} 项）</summary><p className="helper">此处列出全部 CDT 项目，可能同时包含公网与跨地域流量，不按币种混加费用。无账单不代表未开通或没有用量。</p><div className="table-wrap"><table><thead><tr><th>地域 / 实例</th><th>账单项目</th><th>用量</th><th>费用</th></tr></thead><tbody>{account.bill?.rows.map((row, index) => <tr key={index}><td>{row.region || '—'}<br /><code>{row.instance_id || '—'}</code></td><td>{row.billing_item || row.product_type || '—'}</td><td>{row.usage || '—'} {row.unit}</td><td>{row.amount || '—'} {row.currency || '币种未知'}</td></tr>)}</tbody></table></div></details>
          {account.traffic && <details><summary>查看地域读数</summary><div className="cloud-region-list">{account.traffic.regions.map(row => <span key={row.region}>{row.region}：{gb(row.bytes)} GB</span>)}</div></details>}
          <div className="cloud-actions"><button className="text-button" disabled={!available || action.busy || !account.enabled} onClick={() => void action.run(() => api(`/api/plugins/alicloud/accounts/${account.id}/refresh`, 'POST'), overview.reload)}>请求更新</button><button className="text-button" disabled={!available || action.busy} onClick={() => open({ type: 'account', value: account })}>编辑账号与策略</button><button className="text-button danger-text" disabled={!available || action.busy} onClick={() => { action.clearError(); setRemoving({ type: 'accounts', id: account.id, name: account.name }) }}>移除账号</button></div>
        </div>
      </section>)}</div>
      <section className="panel"><div className="panel-heading"><h2>登记的云资源 <span className="subtle">{data.resources.length} / 32</span></h2><button className="button button-secondary button-small" disabled={!available || action.busy || !data.accounts.length || data.resources.length >= 32} onClick={() => open({ type: 'resource' })}>登记资源</button></div>
        {!data.resources.length ? <Empty icon="server" title="尚未登记云资源" description="按账号、地域和资源 ID 登记，不会在阿里云新建资源。" /> : <div className="cloud-resource-list">{data.resources.map(resource => {
          const account = data.accounts.find(a => a.id === resource.account_id), active = data.operations.some(o => o.resource_id === resource.id && ['queued', 'running', 'uncertain'].includes(o.status))
          return <article className="cloud-resource" key={resource.id}><div className="cloud-resource-heading"><div><h3>{resource.name}</h3><code>{resource.cloud_id}</code><span className="subtle"> · {resource.kind === 'ecs' ? 'ECS' : 'EIP'} · {resource.region}</span></div><Badge tone={resource.error_code || active ? 'warm' : 'neutral'}>{active ? '有待处理操作' : resource.error_code ? '查询异常' : resource.snapshot ? '已查询' : '等待查询'}</Badge></div>
            <dl className="cloud-details"><div><dt>云账号</dt><dd>{account?.name ?? '账号已移除'}</dd></div><div><dt>最近带宽 / 计费</dt><dd>{resource.snapshot ? `${resource.snapshot.bandwidth_mbps} Mbps · ${charge(resource.snapshot.charge_type)}` : '尚未查询'}</dd></div><div><dt>公网 IP</dt><dd>{resource.snapshot?.public_ip ?? '—'}</dd></div><div><dt>状态更新时间</dt><dd>{time(resource.checked_at)}</dd></div><div><dt>自动降速</dt><dd>{resource.auto_enabled ? `纳入策略，降至 ${resource.cap_mbps} Mbps${account?.auto_enabled && account.enabled ? '' : '（账号策略未启用）'}` : '未纳入策略'}</dd></div></dl>
            <ErrorNotice message={message(resource.error_code)} /><div className="cloud-actions"><button className="text-button" disabled={!available || action.busy || !account?.enabled} onClick={() => void action.run(() => api(`/api/plugins/alicloud/resources/${resource.id}/refresh`, 'POST'), overview.reload)}>查询当前配置</button><button className="text-button" disabled={!available || action.busy || !account?.enabled || active || (resource.kind === 'eip' && !resource.snapshot)} onClick={() => open({ type: 'bandwidth', value: resource })}>调整带宽与计费</button><button className="text-button" disabled={!available || action.busy} onClick={() => open({ type: 'resource', value: resource })}>编辑策略</button><button className="text-button danger-text" disabled={!available || action.busy || active} onClick={() => { action.clearError(); setRemoving({ type: 'resources', id: resource.id, name: resource.name }) }}>移除登记</button></div>
          </article>
        })}</div>}
      </section>
      <section className="panel"><div className="panel-heading"><h2>变配操作记录</h2><span className="subtle">优先展示待处理及最近 100 条 · 保留 180 天</span></div>{!data.operations.length ? <Empty title="暂无变配操作" description="预览、确认、取消和自动降速记录会显示在这里。" /> : <div className="table-wrap"><table><thead><tr><th>资源 / 时间</th><th>调整内容</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.operations.map(operation => <tr key={operation.id}><td>{data.resources.find(r => r.id === operation.resource_id)?.name ?? operation.before_state.cloud_id}<small className="cloud-block">{time(operation.created_at)} · {operation.source === 'manual' ? '手动' : '自动降速'}</small></td><td>{operation.before_state.bandwidth_mbps} → {operation.target.bandwidth_mbps} Mbps<small className="cloud-block">{charge(operation.before_state.charge_type)} → {charge(operation.target.charge_type)}</small></td><td><Badge tone={operation.status === 'succeeded' ? 'good' : ['uncertain', 'failed'].includes(operation.status) ? 'warm' : 'neutral'}>{status(operation.status)}</Badge>{operation.error_code && <small className="cloud-block">{message(operation.error_code)}</small>}{operation.request_id && <small className="cloud-block">云请求：{operation.request_id}</small>}</td><td>{['preview', 'queued'].includes(operation.status) && <button className="text-button" disabled={!available || action.busy} onClick={() => void action.run(() => api(`/api/plugins/alicloud/operations/${operation.id}/cancel`, 'POST'), overview.reload)}>取消</button>}{operation.status === 'uncertain' && <button className="text-button" disabled={!available || action.busy} onClick={() => { action.clearError(); setVerified(false); setDismiss(operation) }}>已人工核对</button>}</td></tr>)}</tbody></table></div>}</section>
    </>}
    {editing?.type === 'account' && <AccountEditor account={editing.value} available={available} close={() => setEditing(null)} saved={done} />}
    {editing?.type === 'resource' && data && <ResourceEditor resource={editing.value} accounts={data.accounts} available={available} close={() => setEditing(null)} saved={done} />}
    {editing?.type === 'bandwidth' && <BandwidthEditor resource={editing.value} available={available} close={() => setEditing(null)} saved={done} />}
    {removing && <Confirm title={removing.type === 'accounts' ? '移除云账号' : '移除资源登记'} busy={action.busy} error={action.error} confirmDisabled={!available} onClose={() => setRemoving(null)} onConfirm={() => void action.run(() => api(`/api/plugins/alicloud/${removing.type}/${removing.id}`, 'DELETE'), done)}>确认移除“{removing.name}”？这不会删除阿里云资源。账号须先移除全部资源登记；操作历史保留。</Confirm>}
    {dismiss && <Modal title="结束不确定操作的跟踪" busy={action.busy} onClose={() => setDismiss(null)}><div className="modal-body"><ErrorNotice message={action.error} /><p>请先在阿里云控制台核对资源与订单。结束跟踪不会撤销已提交的调整，并会暂停此资源的自动降速，避免立即再次执行。</p><label className="cloud-toggle"><input type="checkbox" checked={verified} onChange={e => setVerified(e.target.checked)} />已核对云端结果，确认结束跟踪</label></div><footer><button className="button button-secondary" disabled={action.busy} onClick={() => setDismiss(null)}>返回</button><button className="button button-primary" disabled={action.busy || !available || !verified} onClick={() => void action.run(() => api(`/api/plugins/alicloud/operations/${dismiss.id}/dismiss`, 'POST'), done)}>结束跟踪并暂停资源策略</button></footer></Modal>}
  </div>
}
