import { useState } from 'react'
import { api } from '../../api'
import { Badge, Confirm, Empty, ErrorNotice, Field, Modal } from '../../components'
import { useAction } from '../../hooks'
import { defaultPowerPolicy, message, powerSource, powerStatus, status, stopMode, time, utcOffset } from './types'
import type { Account, CloudEvent, PowerJob, PowerPolicy, Resource } from './types'
import { checked, operationError, powerError, resourceError } from './guards'
import type { CurrentCloud } from './guards'

type Events = { close: () => void; saved: () => void; available: boolean; current: CurrentCloud; refresh: () => void }
export function PowerPolicyEditor({ resource, close, saved, current }: Events & { resource: Resource }) {
  const [value, setValue] = useState<PowerPolicy>(resource.power_policy ?? defaultPowerPolicy), action = useAction()
  const set = <K extends keyof PowerPolicy>(key: K, next: PowerPolicy[K]) => setValue(previous => ({ ...previous, [key]: next }))
  const [accountRevision] = useState(() => current()?.accounts.find(a => a.id === resource.account_id)?.revision)
  const writeError = () => resourceError(current, resource, { power: true, accountRevision })
  return <Modal title={`自动启停 · ${resource.name}`} busy={action.busy} onClose={close}><form onSubmit={e => { e.preventDefault(); void action.run(() => checked(writeError, () => api(`/api/plugins/alicloud/resources/${resource.id}/power-policy`, 'PATCH', { revision: resource.revision, policy: value })), saved) }}>
    <div className="modal-body"><ErrorNotice message={action.error || writeError()} /><fieldset disabled={action.busy}>
      <label className="cloud-toggle"><input type="checkbox" checked={value.enabled} onChange={e => set('enabled', e.target.checked)} />启用自动启停策略</label>
      <Field label="自动停机模式"><select value={value.stop_mode} onChange={e => set('stop_mode', e.target.value as PowerPolicy['stop_mode'])}><option value="KeepCharging">普通停机（KeepCharging）</option><option value="StopCharging">节省停机（StopCharging）</option></select></Field>
      <p className="helper">普通停机继续收费并保留计算资源。节省停机仍可能收取磁盘等费用，固定公网 IP 可能变化，重新启动依赖库存；不支持时云端可能按普通模式停机，面板会核对实际模式。</p>
      <Field label="流量阈值动作"><select value={value.threshold_action} onChange={e => set('threshold_action', e.target.value as PowerPolicy['threshold_action'])}><option value="off">关闭阈值策略</option><option value="notify">仅通知</option><option value="stop">停机并通知</option></select></Field>
      {value.threshold_action !== 'off' && <><div className="form-grid"><Field label="账号 CDT 月流量额度（GB）"><input required type="number" min={1} max={1000000000} step={1} value={value.limit_gb} onChange={e => set('limit_gb', Number(e.target.value))} /></Field><Field label="触发百分比（%）"><input required type="number" min={1} max={100} step={1} value={value.threshold_percent} onChange={e => set('threshold_percent', Number(e.target.value))} /></Field></div><p className="helper">按账号合计已出账 CDT 用量判断，达到 {value.limit_gb * value.threshold_percent / 100} GB 时触发；云账单有延迟，不能作为实时硬限额。停机保护优先于任何开机，账单失效不会解除保护。通知使用面板设置中的 Telegram / Webhook，事件同时保存在本页。</p></>}
      <label className="cloud-toggle"><input type="checkbox" checked={value.schedule_enabled} onChange={e => set('schedule_enabled', e.target.checked)} />每日定时开关机</label><p className="helper">计划与保活由面板执行，目标停机期间面板需保持在线。</p>
      {value.schedule_enabled && <><div className="form-grid"><Field label="每日开机时间"><input type="time" required value={value.start_time} onChange={e => set('start_time', e.target.value)} /></Field><Field label="每日停机时间"><input type="time" required value={value.stop_time} onChange={e => set('stop_time', e.target.value)} /></Field></div><Field label="计划时区（固定 UTC 偏移分钟）"><input type="number" required min={-720} max={840} step={15} value={value.utc_offset_minutes} onChange={e => set('utc_offset_minutes', Number(e.target.value))} /></Field><p className="helper">当前 {utcOffset(value.utc_offset_minutes)}{value.utc_offset_minutes === 480 ? '（北京时间）' : ''}，不跟随浏览器时区或夏令时。支持跨午夜，仅补执行最近 10 分钟的计划；手动停机后暂停自动开机。</p></>}
      <label className="cloud-toggle"><input type="checkbox" checked={value.keepalive} onChange={e => set('keepalive', e.target.checked)} />抢占式实例保活</label><p className="helper">仅尝试启动仍存在的已停止抢占式实例，不购买或重建资源。遵循流量保护、手动暂停及计划运行时段；明确拒绝后至少等待 15 分钟，结果不确定时只核对状态。</p>
    </fieldset></div><footer><button className="button button-secondary" type="button" disabled={action.busy} onClick={close}>取消</button><button className="button button-primary" disabled={action.busy || Boolean(writeError()) || value.start_time === value.stop_time}>保存启停策略</button></footer>
  </form></Modal>
}
export function PowerEditor({ resource, action: verb, close, saved, current, refresh }: Events & { resource: Resource; action: 'start' | 'stop' }) {
  const [mode, setMode] = useState(resource.power_policy?.stop_mode ?? 'KeepCharging'), [preview, setPreview] = useState<PowerJob | null>(null), [confirmed, setConfirmed] = useState(false), action = useAction()
  const [accountRevision] = useState(() => current()?.accounts.find(a => a.id === resource.account_id)?.revision)
  const writeError = () => powerError(current, resource, verb, accountRevision) || (preview ? operationError(current, preview, true, ['preview'], true) : '')
  return <Modal title={`${verb === 'start' ? '开机' : '停机'} · ${resource.name}`} busy={action.busy} onClose={close}><form onSubmit={e => { e.preventDefault(); if (preview) { if (confirmed) void action.run(() => checked(writeError, () => api(`/api/plugins/alicloud/power-jobs/${preview.id}/confirm`, 'POST')), saved) } else void action.run(() => checked(writeError, () => api<PowerJob>(`/api/plugins/alicloud/resources/${resource.id}/power-preview`, 'POST', { revision: resource.revision, action: verb, stop_mode: mode })), value => { setPreview(value); setConfirmed(false); refresh() }) }}>
    <div className="modal-body"><ErrorNotice message={action.error || writeError()} />{preview ? <><dl className="cloud-details"><div><dt>实例</dt><dd>{preview.before_state.cloud_id} · {preview.before_state.region}</dd></div><div><dt>云端状态</dt><dd>{powerStatus(preview.before_state.status)}</dd></div><div><dt>本次操作</dt><dd>{verb === 'start' ? '开机' : stopMode(preview.stop_mode)}</dd></div><div><dt>预览有效期</dt><dd>{time(preview.expires_at)}</dd></div></dl><label className="cloud-toggle"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />已核对实例，确认执行{verb === 'start' ? '开机并承担运行费用' : '停机及相应收费方式'}</label></> : verb === 'stop' ? <Field label="本次停机模式"><select value={mode} disabled={action.busy} onChange={e => setMode(e.target.value as PowerPolicy['stop_mode'])}><option value="KeepCharging">普通停机（KeepCharging）</option><option value="StopCharging">节省停机（StopCharging）</option></select></Field> : <p>将启动此 ECS 实例并恢复运行计费。节省停机后的固定公网 IP 可能变化，启动依赖可用库存。</p>}
      {verb === 'stop' && <p className="helper">正常关机，不强制断电。普通停机继续收费；节省停机仍可能收取磁盘等费用，并可能释放固定公网 IP。手动停机会暂停计划开机与保活，直到手动开机或恢复自动策略。</p>}<p className="helper">确认后进入任务队列，只有云端状态核对完成才显示成功。已发送的命令不能取消，未知结果不会重复发送。</p>
    </div><footer><button className="button button-secondary" type="button" disabled={action.busy} onClick={preview ? () => { setPreview(null); setConfirmed(false) } : close}>{preview ? '重新预览' : '取消'}</button><button className="button button-primary" disabled={action.busy || Boolean(writeError()) || (!!preview && !confirmed)}>{preview ? '确认执行启停' : '预览启停操作'}</button></footer>
  </form></Modal>
}
export function PowerDetails({ resource }: { resource: Resource }) {
  const p = resource.power_policy, s = resource.power_state
  return <><dl className="cloud-details"><div><dt>实例运行状态</dt><dd>{powerStatus(s?.status)}{s?.locked ? ' · 云端锁定' : ''}{s?.status === 'Stopped' ? ` · ${s.stopped_mode ? stopMode(s.stopped_mode) : '停机模式待核实'}` : ''}</dd></div><div><dt>当前公网 IP（启停查询）</dt><dd>{s ? s.public_ips.join('、') || '未分配' : '尚未查询'}</dd></div><div><dt>启停查询时间</dt><dd>{time(resource.power_checked_at ?? null)}</dd></div><div><dt>自动启停</dt><dd>{p?.enabled ? '已启用' : '已关闭'}{resource.manual_hold ? ' · 手动暂停开机' : ''}{resource.threshold_hold ? ' · 流量停机保护' : ''}</dd></div><div><dt>每日计划</dt><dd>{p?.schedule_enabled ? `${p.start_time} 开机 / ${p.stop_time} 停机 · ${utcOffset(p.utc_offset_minutes)}` : '未启用'}</dd></div><div><dt>抢占式保活</dt><dd>{p?.keepalive ? '已配置' : '未启用'}{s?.spot_strategy === 'NoSpot' ? ' · 当前非抢占式实例' : ''}{s?.interruption_behavior === 'Terminate' ? ' · 云端中断会释放实例，释放后无法保活' : ''}</dd></div></dl><ErrorNotice message={message(resource.power_error)} /></>
}
export function CostDetails({ account, resource }: { account?: Account; resource?: Resource }) {
  if (account) return <><p className="cloud-policy">账户可用额度：<strong>{account.balance ? `${account.balance.available} ${account.balance.currency}` : '尚未查询'}</strong></p><p className="helper">余额缓存：{time(account.balance?.queried_at ?? null)} · 默认每 6 小时更新；可用额度以云端为准，包含账期延迟。旧值不代表当前余额。</p><ErrorNotice message={account.balance_error ? `余额：${message(account.balance_error)}` : ''} /></>
  if (!resource) return null
  const bill = resource.instance_bill, labels: Record<string, string> = { SubscriptionOrder: '预付订单', PayAsYouGoBill: '后付账单', Refund: '退款', Adjustment: '调账' }
  return <details><summary>实例账单与缓存</summary><p className="helper">{bill?.month ?? '当月'} · 更新：{time(bill?.queried_at ?? null)} · 缓存 6 小时，跨月重新查询；不同币种不混加。云账单有延迟，无项目不代表没有费用。</p><ErrorNotice message={message(resource.bill_error)} />{bill?.rows.map((row, index) => <p key={index}>{labels[row.item] ?? '账单项目'}：{row.amount} {row.currency}</p>)}</details>
}
export function PowerHistory({ jobs, resources, events, available, current, reload }: { jobs: PowerJob[]; resources: Resource[]; events: CloudEvent[]; available: boolean; current: CurrentCloud; reload: () => void }) {
  const action = useAction(), [dismiss, setDismiss] = useState<PowerJob | null>(null)
  return <><section className="panel"><div className="panel-heading"><h2>启停任务</h2><span className="subtle">最近 100 条 · 保留 180 天</span></div><ErrorNotice message={action.error} />{!jobs.length ? <Empty title="暂无启停任务" description="手动、阈值、每日计划与保活任务会显示在这里。" /> : <div className="table-wrap"><table><thead><tr><th>实例 / 时间</th><th>操作与来源</th><th>状态</th><th>操作</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td>{resources.find(r => r.id === job.resource_id)?.name ?? job.before_state.cloud_id}<small className="cloud-block">{time(job.created_at)}</small></td><td>{job.action === 'start' ? '开机' : stopMode(job.stop_mode)}<small className="cloud-block">{powerSource(job.source)}</small></td><td><Badge tone={job.status === 'succeeded' ? 'good' : ['failed', 'uncertain'].includes(job.status) ? 'warm' : 'neutral'}>{job.status === 'failed' ? '未按预期完成' : status(job.status)}</Badge><small className="cloud-block">{message(job.error_code)}</small>{job.request_id && <small className="cloud-block">云请求：{job.request_id}</small>}</td><td>{['preview', 'queued'].includes(job.status) && <button className="text-button" disabled={!available || action.busy} onClick={() => void action.run(() => checked(() => operationError(current, job, true, ['preview', 'queued']), () => api(`/api/plugins/alicloud/power-jobs/${job.id}/cancel`, 'POST')), reload)}>取消任务</button>}{job.status === 'uncertain' && <button className="text-button" disabled={!available || action.busy} onClick={() => setDismiss(job)}>核对并结束跟踪</button>}</td></tr>)}</tbody></table></div>}</section>
    <section className="panel"><div className="panel-heading"><h2>云资源通知</h2><a href="#/system/settings">配置通知渠道</a></div>{!events.length ? <Empty title="暂无云资源事件" description="流量阈值和启停结果保存在这里，并发送到已启用的 Telegram / Webhook。" /> : <div className="panel-body">{events.map(event => <article className="cloud-event" key={event.id}><strong>{event.title} · {resources.find(r => r.id === event.resource_id)?.name ?? '已移除资源'}</strong><p>{event.message}</p><small className="subtle">{time(event.created_at)}{event.deliveries.length === 0 ? ' · 未配置外部通知，仅保存站内事件' : ''}</small>{event.deliveries.map(d => <p className="helper" key={d.channel}>{d.channel === 'telegram' ? 'Telegram' : 'Webhook'}：{({ pending: '等待投递', sent: '已送达', failed: '投递失败', cancelled: '已取消' })[d.status] ?? '状态未知'} · 尝试 {d.attempts} 次{d.last_error ? ` · ${d.last_error}` : ''}</p>)}</article>)}</div>}</section>
    {dismiss && <Confirm title="结束启停跟踪" confirmLabel="结束跟踪" busyLabel="正在处理…" busy={action.busy} error={action.error} confirmDisabled={Boolean(operationError(current, dismiss, true, ['uncertain']))} onClose={() => setDismiss(null)} onConfirm={() => void action.run(() => checked(() => operationError(current, dismiss, true, ['uncertain']), () => api(`/api/plugins/alicloud/power-jobs/${dismiss.id}/dismiss`, 'POST')), () => { setDismiss(null); reload() })}>请先在阿里云核对实例状态及收费模式。结束跟踪不会撤回命令，会暂停此资源的自动启停和降速，并保留手动暂停标记。</Confirm>}
  </>
}
