import { useEffect } from 'react'
import { Badge, ErrorNotice, Loading, Refresh } from '../components'
import { useResource } from '../hooks'
import { time } from '../format'

type Channel = { channel: 'telegram' | 'webhook'; configured: boolean; enabled: boolean; notification_enabled: boolean; counts: { pending: number; failed: number; sent: number; next_attempt_at: number | null }; last_delivery: { status: string; attempts: number; last_error: string | null; attempted_at: number } | null; test: { attempted_at: number; success: boolean | null; last_error: string | null } | null }
export default function NotificationChannels() {
  const resource = useResource<Channel[]>('/api/notifications/channels', 15_000)
  useEffect(() => { window.addEventListener('sinan:notifications-updated', resource.reload); return () => window.removeEventListener('sinan:notifications-updated', resource.reload) }, [resource.reload])
  return <section className="panel notification-channels"><div className="panel-body"><div className="notification-heading"><h2>渠道投递状态</h2><Refresh onClick={resource.reload} /></div><p className="helper">自动消息最多尝试 8 次；限流时遵守服务返回的等待时间。统计对应当前保留的历史，修改配置后不会补发过去事件。</p><ErrorNotice message={resource.error} retry={resource.reload} />{resource.loading && !resource.data ? <Loading /> : <div className="notification-channel-grid">{resource.data?.map(channel => <article key={channel.channel}><div className="notification-heading"><strong>{channel.channel === 'telegram' ? 'Telegram' : 'Webhook'}</strong><Badge tone={channel.configured && channel.enabled && channel.notification_enabled ? 'good' : 'neutral'}>{!channel.configured ? '未配置' : !channel.notification_enabled ? '总通知已关闭' : channel.enabled ? '自动通知已启用' : '自动通知已停用'}</Badge></div><p>待发送 {channel.counts.pending} · 已发送 {channel.counts.sent} · 失败 {channel.counts.failed}</p>{channel.counts.pending > 0 && channel.counts.next_attempt_at !== null && <small>下次尝试：{time(channel.counts.next_attempt_at)}</small>}{channel.last_delivery && <small>最近投递：{time(channel.last_delivery.attempted_at)} · {channel.last_delivery.status === 'sent' ? '已发送' : channel.last_delivery.status === 'failed' ? '重试次数已用尽' : channel.last_delivery.status === 'cancelled' ? '已取消' : '等待重试'}{channel.last_delivery.last_error && ` · ${channel.last_delivery.last_error}`}</small>}{channel.test && <small>最近测试：{time(channel.test.attempted_at)} · {channel.test.success === true ? '服务已接受' : channel.test.success === false ? '未成功' : '等待结果或测试中断'}{channel.test.last_error && ` · ${channel.test.last_error}`}</small>}</article>)}</div>}</div></section>
}
