import { useState } from 'react'
import { Badge, Empty, ErrorNotice, Field, Loading, PageHeader, Refresh } from '../components'
import { useResource } from '../hooks'
import { time } from '../format'
import './monitoring.css'

type Event = { id: number; category: 'offline' | 'resource' | 'expiry' | 'traffic'; message: string; details?: { recovery?: { message?: string } }; server_id: number; server_name: string; last_seen: number | null; opened_at: number; resolved_at: number | null; resolution: string | null; deliveries: { id: number; channel: string; next_attempt_at: number; last_attempt_at: number | null; delivered_at: number | null; kind: string; status: string; attempts: number; last_error: string | null }[] }
const statuses: Record<string, string> = { pending: '等待发送或重试', sent: '已发送', failed: '发送失败', cancelled: '已取消' }
const categories = { offline: '服务器离线', resource: '资源超限', expiry: '到期提醒', traffic: '流量提醒' }
export default function Notifications() {
  const resource = useResource<Event[]>('/api/notifications', 15_000)
  const [category, setCategory] = useState('all'), [state, setState] = useState('all')
  const events = resource.data?.filter(event => (category === 'all' || (event.category ?? 'offline') === category) && (state === 'all' || (state === 'active' ? event.resolved_at === null : event.resolved_at !== null)))
  return <><PageHeader eyebrow="服务器监控" title="告警通知" description="展示最近 200 条事件，已关闭事件保留 90 天。采样缺失时保留原告警，待有效数据确认恢复。"><Refresh onClick={resource.reload} /><a className="button button-secondary" href="#/system/settings">通知设置</a></PageHeader><ErrorNotice message={resource.error} retry={resource.reload} />
    <div className="monitoring-filters"><Field label="事件类型"><select value={category} onChange={event => setCategory(event.target.value)}><option value="all">全部类型</option>{Object.entries(categories).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="事件状态"><select value={state} onChange={event => setState(event.target.value)}><option value="all">全部状态</option><option value="active">尚未结束</option><option value="closed">已结束</option></select></Field></div>
    <section className="panel">{resource.loading && !resource.data ? <Loading /> : !events?.length ? <Empty icon="check" title="暂无符合条件的告警" description="可在通知设置中配置离线、资源、到期和流量提醒。" /> : <div className="table-wrap"><table><thead><tr><th>服务器 / 类型</th><th>状态</th><th>告警内容</th><th>触发 / 结束时间</th><th>渠道投递</th></tr></thead><tbody>{events.map(event => <tr key={event.id}><td><a href={`#/servers/${event.server_id}`}>{event.server_name}</a><small>{categories[event.category ?? 'offline']} · 事件 #{event.id}</small></td><td><Badge tone={event.resolved_at ? 'neutral' : 'bad'}>{!event.resolved_at ? (event.category === 'offline' || !event.category ? '持续离线' : '提醒中') : event.resolution === 'recovered' ? '已恢复或结束' : '告警已关闭'}</Badge></td><td style={{ whiteSpace: 'normal', minWidth: 180, maxWidth: 360 }}>{event.message || '设备持续离线，等待重新上报。'}{event.details?.recovery?.message && <small>恢复时：{event.details.recovery.message}</small>}{(event.category === 'offline' || !event.category) && event.last_seen && <small>最后在线：{time(event.last_seen)}</small>}</td><td>{time(event.opened_at)}<small>{time(event.resolved_at)}</small></td><td>{!event.deliveries.length ? '未发送' : event.deliveries.map(item => <div className="notification-delivery" key={item.id ?? `${item.channel}-${item.kind}`}>{item.channel === 'webhook' ? 'Webhook' : 'Telegram'} · {item.kind === 'recovery' ? '恢复' : '告警'}：{statuses[item.status] ?? item.status}{item.attempts > 0 && `（${item.attempts} 次）`}{item.status === 'pending' && item.next_attempt_at && <small>下次尝试：{time(item.next_attempt_at)}</small>}{item.delivered_at && <small>发送时间：{time(item.delivered_at)}</small>}{item.last_error && <small>{item.last_error}</small>}</div>)}</td></tr>)}</tbody></table></div>}</section></>
}
