import { useState } from 'react'
import { AgentSettings } from './AgentSettings'
import AgentTasks from './AgentTasks'
import { api } from '../api'
import { Badge, CopyField, Empty, ErrorNotice, Field, Icon, Loading, Modal, PageHeader, Refresh, Stat } from '../components'
import { bytes, navigate, percent, time, uptime } from '../format'
import { useAction, useResource } from '../hooks'
import type { Deployment, Enrollment, Node, Server } from '../types'
import ServerNavigation from './ServerNavigation'

export default function ServerDetail({ id }: { id: number }) {
  const server = useResource<Server>(`/api/servers/${id}`)
  const deployment = useResource<Deployment>(`/api/servers/${id}/deployments`)
  const nodes = useResource<Node[]>('/api/nodes')
  const action = useAction()
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null)
  const [installing, setInstalling] = useState(false)
  const [agentVersion, setAgentVersion] = useState('')
  const enroll = (version = agentVersion) => {
    setEnrollment(null)
    const query = version.trim() ? `?agent_version=${encodeURIComponent(version.trim())}` : ''
    void action.run(() => api<Enrollment>(`/api/servers/${id}/enrollment${query}`, 'POST'), setEnrollment)
  }
  const refresh = () => { server.reload(); deployment.reload(); nodes.reload() }
  const entry = server.data
  const status = deployment.data?.status
  if (!entry) return <><button className="back-link" onClick={() => navigate('/servers')}><Icon name="back" size={16} />返回服务器</button><ErrorNotice message={server.error} retry={server.reload} />{server.loading && <Loading />}</>
  const metrics = entry.latest_metrics, info = entry.static_info
  const rows = [['操作系统', info.system], ['内核版本', info.kernel], ['系统架构', info.arch], ['主机名', info.hostname], ['处理器型号', info.cpu_model], ['核心数', info.cpu_cores], ['总内存', info.memory_total === undefined ? undefined : bytes(info.memory_total)], ['磁盘容量', info.disk_total === undefined ? undefined : bytes(info.disk_total)], ['虚拟化', info.virtualization], ['Agent 版本', info.agent_version], ['运行时版本', info.runtime_version], ['最近设备消息', entry.last_seen ? time(entry.last_seen) : undefined], ['最后心跳', entry.last_heartbeat_at ? time(entry.last_heartbeat_at) : '尚未记录'], ['最后指标', entry.metrics_sampled_at ? time(entry.metrics_sampled_at / 1000) : Object.keys(metrics).length ? '时间未知' : '尚未上报']]
  return <>
    <button className="back-link" onClick={() => navigate('/servers')}><Icon name="back" size={16} />返回服务器</button>
    <PageHeader eyebrow={`服务器 #${entry.id}`} title={entry.name} description="系统概况、运行指标与每一次配置部署。"><Badge tone={entry.online ? 'good' : 'neutral'}>{entry.online ? '在线' : entry.device_public_key ? '离线' : '待接入'}</Badge>{entry.metrics_stale && <Badge tone="warm">指标过期</Badge>}<Refresh onClick={refresh} /><button className="button button-primary" onClick={() => { setInstalling(true); setAgentVersion(''); enroll('') }}><Icon name="plus" size={16} />接入 / 升级</button></PageHeader>
    <ServerNavigation id={id} active="overview" />
    <ErrorNotice message={server.error || deployment.error || nodes.error} retry={refresh} />
    {!entry.online && <div className="notice">{entry.device_public_key ? '设备当前离线，以下指标是最近一次上报的数据。' : '设备尚未接入。点击“接入 / 升级”获取安装命令。'}</div>}
    {entry.metrics_stale && <div className="notice">指标过期，以下保留的是最后一次采集的历史数据。最后指标时间：{entry.metrics_sampled_at ? time(entry.metrics_sampled_at / 1000) : '未知'}。心跳独立更新，在线状态不代表指标仍在采集。</div>}
    <div className="stats-grid stats-four"><Stat icon="activity" label="处理器使用率" value={percent(metrics.cpu_percent)} note={metrics.load_1 === undefined ? '负载尚未上报' : `1 分钟负载 ${metrics.load_1.toFixed(2)}`} /><Stat icon="server" label="已用内存" value={bytes(metrics.memory_used)} note={info.memory_total === undefined ? '总量尚未上报' : `总计 ${bytes(info.memory_total)}`} /><Stat icon="box" label="已用磁盘" value={bytes(metrics.disk_used)} note={info.disk_total === undefined ? '总量尚未上报' : `总计 ${bytes(info.disk_total)}`} /><Stat icon="check" label="运行时间" value={uptime(metrics.uptime_secs)} note="自系统最近一次启动" /></div>
    <div className="detail-grid"><section className="panel"><div className="panel-heading"><h2>配置部署</h2>{status && <Badge tone={status.healthy ? 'good' : status.applied_rev ? 'bad' : 'warm'}>{status.healthy ? '当前配置健康' : status.applied_rev ? '健康检查未通过' : '等待应用'}</Badge>}</div>{deployment.loading && !deployment.data ? <Loading /> : !status ? <Empty icon="nodes" title="还没有发布记录" description="创建节点后，面板会自动编译配置并通知设备。" /> : <div className="panel-body"><div className="revision-grid"><div><span>目标版本</span><strong><small>版本</small> {status.target_rev}</strong></div><Icon name="arrow" /><div><span>已应用版本</span><strong><small>版本</small> {status.applied_rev || '—'}</strong></div></div>{status.last_error && <div className="notice notice-error"><div><strong>最近一次部署失败</strong><p className="break-all">{status.last_error}</p>{status.healthy && <p>旧配置仍健康，节点继续使用上次成功应用的版本。</p>}</div></div>}{status.target_rev > status.applied_rev && !status.last_error && <div className="notice">正在等待设备应用最新配置。设备离线时会在重连后继续。</div>}<div className="detail-caption">最后更新 {time(status.updated_at)}</div></div>}</section><section className="panel"><div className="panel-heading"><h2>连接概况</h2><Icon name="activity" size={18} /></div><div className="panel-body"><dl className="detail-list"><div><dt>TCP 连接数</dt><dd>{metrics.tcp_connections ?? '暂无数据'}</dd></div><div><dt>UDP 连接数</dt><dd>{metrics.udp_connections ?? '暂无数据'}</dd></div><div><dt>系统负载（1 / 5 / 15 分钟）</dt><dd>{[metrics.load_1, metrics.load_5, metrics.load_15].map(value => value?.toFixed(2) ?? '—').join(' / ')}</dd></div><div><dt>面板期望版本</dt><dd>{entry.manifest_rev || '尚未发布'}</dd></div></dl><p className="helper">服务器网卡流量与代理用户流量分别统计。</p></div></section></div>
    <AgentSettings serverId={id} />
    <section className="panel"><div className="panel-heading"><h2>扩展系统指标</h2></div><div className="panel-body"><dl className="detail-list"><div><dt>SWAP</dt><dd>{bytes(metrics.swap_used)} / {bytes(metrics.swap_total)}</dd></div><div><dt>进程数</dt><dd>{metrics.processes ?? '暂无数据'}</dd></div></dl></div>
      {metrics.disks?.length ? <div className="table-wrap"><table><thead><tr><th>磁盘 / 挂载点</th><th>读速率</th><th>写速率</th><th>读 / 写 IOPS</th><th>等待 / 利用率</th></tr></thead><tbody>{metrics.disks.map((disk, index) => <tr key={`${disk.name}-${index}`}><td>{disk.name}<small>{disk.mount_point}</small></td><td>{disk.read_bytes_per_sec == null ? '暂无数据' : `${bytes(disk.read_bytes_per_sec)}/秒`}</td><td>{disk.write_bytes_per_sec == null ? '暂无数据' : `${bytes(disk.write_bytes_per_sec)}/秒`}</td><td>{disk.read_iops?.toFixed(1) ?? '—'} / {disk.write_iops?.toFixed(1) ?? '—'}</td><td>{disk.await_ms?.toFixed(1) ?? '—'} 毫秒 / {disk.utilization_percent?.toFixed(1) ?? '—'}%</td></tr>)}</tbody></table></div> : <div className="inline-empty">设备尚未上报逐磁盘指标。</div>}
      {metrics.gpus?.length ? <div className="table-wrap"><table><thead><tr><th>GPU</th><th>使用率</th><th>显存</th></tr></thead><tbody>{metrics.gpus.map((gpu, index) => <tr key={index}><td>{gpu.model}</td><td>{gpu.usage_percent?.toFixed(1) ?? '暂无数据'}{gpu.usage_percent != null && '%'}</td><td>{bytes(gpu.memory_used ?? undefined)} / {bytes(gpu.memory_total ?? undefined)}</td></tr>)}</tbody></table></div> : <div className="inline-empty">暂无 GPU 数据。</div>}
    </section>
    <AgentTasks key={id} serverId={id} commandsEnabled={Array.isArray(entry.capabilities) && entry.capabilities.includes('command:execute')} />
    <section className="panel"><div className="panel-heading"><h2>系统信息</h2><span className="subtle">缺失字段显示暂无数据</span></div><dl className="info-grid">{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value ?? '暂无数据'}</dd></div>)}</dl></section>
    <section className="panel"><div className="panel-heading"><h2>网络接口</h2><span className="subtle">服务器层面的累计计数</span></div>{Object.keys(metrics.network_interfaces ?? {}).length ? <div className="table-wrap"><table><thead><tr><th>接口</th><th>累计接收</th><th>累计发送</th><th>接收速率</th><th>发送速率</th></tr></thead><tbody>{Object.entries(metrics.network_interfaces ?? {}).map(([name, metric]) => <tr key={name}><td className="mono">{name}</td><td>{bytes(metric.received_bytes)}</td><td>{bytes(metric.transmitted_bytes)}</td><td>{metric.receive_bytes_per_sec === undefined ? '暂无数据' : `${bytes(metric.receive_bytes_per_sec)}/秒`}</td><td>{metric.transmit_bytes_per_sec === undefined ? '暂无数据' : `${bytes(metric.transmit_bytes_per_sec)}/秒`}</td></tr>)}</tbody></table></div> : <div className="inline-empty">设备尚未上报网络接口信息。</div>}</section>
    <section className="panel"><div className="panel-heading"><h2>部署历史</h2><span className="subtle">最近 6 次发布</span></div>{deployment.data?.history.length ? <div className="table-wrap"><table><thead><tr><th>版本</th><th>模块</th><th>配置包摘要</th><th>发布时间</th></tr></thead><tbody>{deployment.data.history.slice(0, 6).map(item => <tr key={item.rev}><td><strong>版本 {item.rev}</strong>{item.rev === status?.applied_rev && <span className="inline-tag">已应用</span>}</td><td>代理运行时</td><td><code title={item.bundle_sha256}>{item.bundle_sha256.slice(0, 16)}…</code></td><td>{time(item.created_at)}</td></tr>)}</tbody></table></div> : <div className="inline-empty">还没有发布记录。</div>}</section>
    <section className="panel"><div className="panel-heading"><h2>此服务器的节点</h2><button className="text-button" onClick={() => navigate('/nodes')}>管理节点 <Icon name="arrow" size={14} /></button></div><div className="node-chips">{nodes.data?.filter(node => node.server_id === id).map(node => <span key={node.id}><Icon name="nodes" size={16} /><strong>{node.name}</strong><code>:{node.port}</code></span>)}{!nodes.data?.some(node => node.server_id === id) && <p className="subtle">尚未创建节点。</p>}</div></section>
    {installing && <Modal title="接入或升级设备" onClose={() => setInstalling(false)} busy={action.busy} wide><div className="modal-body"><Field label="Agent 版本" hint="留空选择最新的兼容签名版本；也可以指定已导入的版本。"><input value={agentVersion} onChange={event => setAgentVersion(event.target.value)} maxLength={96} placeholder="例如：0.3.0" disabled={action.busy} /></Field><button className="button button-secondary" disabled={action.busy} onClick={() => enroll()}>生成所选版本的命令</button><ErrorNotice message={action.error} />{enrollment ? <><p className="confirm-copy">在服务器上以 root 身份执行。升级时会保留原有设备身份和本地状态。</p><p className="helper">先按部署文档核对发布公钥并准备可信 sinan-bootstrap。旧的未签名缓存需要先完成迁移；预检失败会保留当前安装。</p>{enrollment.install_command ? <><p className="helper">目标 Agent 版本：{enrollment.installation?.version}</p><CopyField text={enrollment.install_command} label="复制安装命令" /></> : <ErrorNotice message={enrollment.warning ?? "请先导入已签名的 Agent 制品"} />}<p className="helper">令牌有效至 {time(enrollment.expires_at)}，仅供此设备使用。</p></> : action.busy ? <Loading /> : <button className="button button-secondary" onClick={() => enroll()}>重试</button>}</div><footer><button className="button button-secondary" disabled={action.busy} onClick={() => setInstalling(false)}>关闭</button></footer></Modal>}
  </>
}
